
{{- if .Values.service.enabled -}}
{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  host: {{ template "hostname" .Values.service.url }}
  {{- if .Values.route.tls.enabled }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge  
  {{- end }}
  to:
    kind: Service
    name: {{ template "fullname" . }}
    weight: 100
{{- end -}}
{{- end -}}