{{- if .Values.frontend.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname-frontend" . }}
{{- if .Values.frontend.service.annotations }}
  annotations:
{{ toYaml .Values.frontend.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "appname-frontend" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.externalPort }}
    targetPort: {{ .Values.frontend.service.internalPort }}
    protocol: TCP
    name: {{ .Values.frontend.service.name }}
  selector:
    app: {{ template "appname-frontend" . }}
    tier: "{{ .Values.frontend.application.tier }}"
{{- end -}}
